boostcampwm-2021/iOS05-Escaper

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Domain/DataStruct/Genre.swift
- Escaper/Escaper/Domain/DataStruct/Room.swift
- Escaper/Escaper/Domain/UseCase/RoomListUseCase.swift
- Escaper/Escaper/Info.plist
- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
- Escaper/Escaper/Presentation/RoomList/RoomListViewModel.swift
issue number : [#16](../issues/16)
- 다크모드 사용 하지 않음
- MVVM Interface 정의
close #16
> Architecture Design - Interface 정의

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Common/Library/ColorPalette.swift
- Escaper/Escaper/Resources/Assets.xcassets/Palette/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/bloodyBlack.colorset/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/bloodyBurgundy.colorset/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/bloodyRed.colorset/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/charcoal.colorset/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/gloomyPink.colorset/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/gloomyPurple.colorset/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/gloomyRed.colorset/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/pumpkin.colorset/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/skullLightWhite.colorset/Contents.json
- Escaper/Escaper/Resources/Assets.xcassets/Palette/skullWhite.colorset/Contents.json
issue number : [#19](../issues/19)
- Color Asset 추가
- Color enum 생성
close #19
> [E03 T12] 색상 Asset을 추가한다.

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Escaper/Escaper/Domain/DataStruct/Genre.swift
- Escaper/Escaper/Domain/DataStruct/GeoLocation.swift
- Escaper/Escaper/Domain/DataStruct/Room.swift
- Escaper/Escaper/Domain/DataStruct/UserRecord.swift
- Escaper/Escaper/GoogleService-Info.plist
issue number : [#06](../issues/06)
- cloud firestore spm 추가
- firestore 통신을 위한 모델 추가
[파이어스토어 문서](https://firebase.google.com/docs/firestore/manage-data/add-data)  
close #6
> [E03 T09] 방탈출 방의 Database를 설계한다.

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Common/DefaultViewController.swift
- Escaper/Escaper/Domain/DataStruct/Genre.swift
- Escaper/Escaper/Domain/DataStruct/SortingOption.swift
- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
- Escaper/Escaper/Presentation/RoomList/RoomListViewModel.swift
- Escaper/Escaper/Presentation/RoomList/Views/TagButton.swift
- Escaper/Escaper/Presentation/RoomList/Views/TagScrollView.swift
- Escaper/Escaper/Resources/Assets.xcassets/Palette/bloodyDarkBurgundy.colorset/Contents.json
issue number : [#05](../issues/05)
- TagScrollView 구현
- RoomListViewController 구현
close #5
> [E03 T03] 장르 CollectionView (FlowLayout, UICollectionViewDataSource)를 구현한다.

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Domain/DataStruct/District.swift
- Escaper/Escaper/Domain/DataStruct/GeoLocation.swift
- Escaper/Escaper/Domain/DataStruct/Room.swift
- Escaper/Escaper/Domain/UseCase/RoomListUseCase.swift
- Escaper/Escaper/Info.plist
- Escaper/Escaper/Infrastructure/FirebaseService.swift
- Escaper/Escaper/Infrastructure/RoomDTO.swift
- Escaper/Escaper/Infrastructure/RoomListRepository.swift
- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
issue number : [#12](../issues/12)
close #12 
Room, RoomDTO 모델 구현
FirebaseService 구현
RoomListRepository 구현
RoomListUseCase 구현
> [E03 T11] 데이터와 파이어베이스를 연동한다.

- Escaper/Escaper/Info.plist
issue number : [#31](../issues/31)
close #31
statusbar 색상 화이트로 고정
[iOS. StatusBar 색상, 보이기를 조절합시다](https://mrgamza.tistory.com/630)
> [E03 T15] status Bar의 색상을 고정한다

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Infrastructure/FirebaseService.swift
- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
- Escaper/Escaper/Presentation/RoomList/Views/Cells/RoomOverviewTableViewCell.swift
issue number : [#43](../issues/43)
close #43
SwiftLint auto fix 제거
암시적 옵셔널 제거
빌드 버전 0.2로 변경
> 암시적 옵셔널 제거 및 SwiftLint auto 제거

- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
- Escaper/Escaper/Presentation/RoomList/Views/Cells/RoomOverviewTableViewCell.swift
issue number : [#46](../issues/46)
close #46
- RoomOverviewTableViewCell 오토레이아웃 개선
- RoomOverviewTableViewCell distance 추가
distance를 string으로 변경할 때 삼항연산자를 사용 및 Constant 네이밍 리뷰 부탁드립니다.
- 아이폰se 화면
> Style: RoomOverviewTableViewCell 스타일 변경

- Escaper/Escaper/Domain/UseCase/RoomListUseCase.swift
- Escaper/Escaper/Info.plist
- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
- Escaper/Escaper/Presentation/RoomList/RoomListViewModel.swift
- Escaper/Escaper/Presentation/RoomList/Views/TagScrollView.swift
issue number : [#48](../issues/48)
close #48
- ViewController에서 위치정보를 요청한다.
- 위치 정보를 요청하고, 만약 위치정보가 변경되었을 때, 현재 필터를 기반으로 요청할 수 있도록 한다.
- Usecase에서 district 정보를 받을 수 있도록 한다.
> CLLocation ViewController로 이전, Usecase query에 district 추가하여 요청

- Escaper/Escaper/Domain/DataStruct/SortingOption.swift
- Escaper/Escaper/Presentation/RoomList/Views/TagButton.swift
- Escaper/Escaper/Presentation/RoomList/Views/TagScrollView.swift
issue number : [#30](../issues/30)
close #30
sortingOption tag 이름을 바꾸고 tag와 tagScroll의 UI를 개선하였다.
> [E03 T14] 태그 UI를 수정한다. (Color, Border, FontSize, 양쪽 VIew 크기)

- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
issue number : [#51](../issues/51)  [#52](../issues/52)
close #51 #52 
- RoomListController에서 테이블 뷰 셀을 클릭시 DetailVIewController를 생성, 업데이트, push를 해줍니다.
> [E8 S1 T2] 모두보기 화면에서 화면이 넘어온다.

- Escaper/Escaper/Info.plist
issue number : [#34](../issues/34)
close #34
- Info.plist에서 작업
- 아이패드, 맥, 아이폰  모두 portrait 적용.
> [E3 S1 T18] 세로로 화면이 고정될 수 있도록 수정한다.

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Application/AppDelegate.swift
- Escaper/Escaper/Common/Library/Helper.swift
- Escaper/Escaper/Domain/DataStruct/Record.swift
- Escaper/Escaper/Domain/DataStruct/RecordInfo.swift
- Escaper/Escaper/Domain/UseCase/RecordUsecase.swift
- Escaper/Escaper/Infrastructure/DataMapping/RecordInfoDTO.swift
- Escaper/Escaper/Infrastructure/FirebaseService.swift
- Escaper/Escaper/Infrastructure/ImageCacheManager.swift
- Escaper/Escaper/Infrastructure/NetworkService.swift
issue number : [#71](../issues/71)
close #71
- RecordInfo imageUrl 추가
- Record imageUrl 추가
- RecordInfoDTO imageUrl 추가
- Firebase Storage 연동하여 이미지 추가 가능
- Image Cache manager를 사용하여 이미지 캐싱
> [E4 S1 T7] 이미지를 캐싱 및 다운로드한다.

- .gitignore
- Escaper/Escaper/Presentation/Record/RecordViewController.swift
> 기록 화면 리뷰반영 2

- Escaper/Escaper/Application/Base.lproj/LaunchScreen.storyboard
issue number : [#101](../issues/101)
close #101
런치스크린 구현
<br>
> [E9 T1] 런치스크린 구현한다.

- Escaper/Escaper/Common/Extensions/UISearchBar+SetTextFieldColor.swift
- Escaper/Escaper/Presentation/AddRecord/AddRecordViewController.swift
- Escaper/Escaper/Presentation/AddRecord/View/RecordView.swift
- Escaper/Escaper/Presentation/FindRoom/FindRoomViewController.swift
- Escaper/Escaper/Presentation/FindRoom/FindRoomViewModel.swift
- Escaper/Escaper/Presentation/Record/RecordViewModel.swift
> 기록추가 화면 리뷰사항 반영

- Escaper/Escaper/Presentation/Common/MainTabBarController.swift
Fix: 탭바 백그라운드컬러 추가
iOS15에서 탭바의 백그라운드 컬러는 appearance로 안됨..
> Fix: 탭바 백그라운드컬러 추가

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Application/SceneDelegate.swift
- Escaper/Escaper/DataInjection/DataInjection.swift
- Escaper/Escaper/DataInjection/InjectionDTOs.swift
- Escaper/Escaper/Domain/Entities/Store.swift
- Escaper/Escaper/Domain/Entities/StoreRegion.swift
- Escaper/Escaper/Infrastructure/DataMapping/StoreDTO.swift
- Escaper/Escaper/Resources/extra.json
issue number : [#135](../issues/135)
close #135 
StoreRegion 추가
> [Common] StoreRegion Entity 추가

- Escaper/Escaper/Common/Library/Helper.swift
- Escaper/Escaper/Presentation/LeaderBoard/LeaderBoardViewController.swift
- Escaper/Escaper/Presentation/LeaderBoard/Views/TopRankView.swift
- Escaper/Escaper/Presentation/RoomDetail/RoomDetailViewController.swift
- Escaper/Escaper/Presentation/RoomDetail/Views/RoomDetailUserRankView.swift
- Escaper/Escaper/Presentation/RoomList/Views/Cell/RoomOverviewTableViewCell.swift
- Escaper/Escaper/Presentation/RoomList/Views/DistrictSelectButton.swift
- Escaper/Escaper/Presentation/RoomList/Views/TagButton.swift
- Escaper/Escaper/Presentation/RoomList/Views/TagScrollView.swift
> VoiceOver 적용 [리더보드, 홈 리스트] 

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Presentation/StoreDetail/StoreDetailViewController.swift
- Escaper/Escaper/Presentation/StoreDetail/Views/HorizontalLineView.swift
- Escaper/Escaper/Presentation/StoreDetail/Views/InfoDescriptionDetailStackView.swift
- Escaper/Escaper/Presentation/StoreDetail/Views/InfoDescriptionStackView.swift
issue number : [#138](../issues/138)
close #138
- 가로 행에 해당하는 stackView를 세로 stackView에 추가하는 방향으로 구현
- 선의 경우 layer를 사용하지 않고, UIView에 height를 상수로 주어 추가하는 방향으로 구현
- 일단 mock 객체로 구현, PR에 남겨둔 이유는 추후 모두가 확인이 가능하게 하기 위함임
- 없음
> [E8 S1 T1] stackView로 세부 정보를 구성한다.

- Escaper/Escaper/Domain/Entities/Room.swift
- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
- Escaper/Escaper/Presentation/StoreDetail/StoreDetailViewController.swift
- Escaper/Escaper/Presentation/StoreDetail/Views/HorizontalLineView.swift
- Escaper/Escaper/Presentation/StoreDetail/Views/InfoDescriptionDetailStackView.swift
issue number : [#144](../issues/144)
close #144
- TableView로 해당 업체의 방을 보여줄 수 있도록 구현
- 이전에 사용한 요소를 재사용함
- 리뷰를 반영함
> [E9 S2 T1] TableView를 사용하여 방정보를 표현한다.

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Application/SceneDelegate.swift
- Escaper/Escaper/Domain/Interface/Repositories/RoomListRepositoryInterface.swift
- Escaper/Escaper/Domain/UseCase/RecordUsecase.swift
- Escaper/Escaper/Domain/UseCase/RoomListUseCase.swift
- Escaper/Escaper/Infrastructure/RoomListRepository.swift
- Escaper/Escaper/Presentation/StoreDetail/StoreDetailViewController.swift
- Escaper/Escaper/Presentation/StoreDetail/StoreDetailViewModel.swift
- Escaper/Escaper/Presentation/StoreDetail/Views/InfoDescriptionDetailStackView.swift
issue number : [#139](../issues/139)
close #139
- 실제 데이터를 받아서 콜렉션 뷰에 그려줌
- RoomList Usecase에 해당 interface를 추가함.
- 추후에 RoomListUsecase의 이름을 변경해야 할 것으로 보임
> [E9 S2 T2] ViewModel, Usecase를 구현한다. 실제 네트워크 요청을 받는다.

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Infrastructure/UserSupervisor.swift
issue number : [#155](../issues/155)
close #155
- HomeViewController, RecordViewController, LeaderBoardViewController에서 사용하는 유저의 로그인 여부를 판단하는 객체를 구현함
> Login 여부를 판단할 수 있는 Singleton 객체를 구현한다.

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Domain/Entities/User.swift
- Escaper/Escaper/Domain/Interface/Repositories/LeaderBoardRepositoryInterface.swift
- Escaper/Escaper/Domain/UseCase/LeaderBoardUseCase.swift
- Escaper/Escaper/Infrastructure/FirebaseService.swift
- Escaper/Escaper/Infrastructure/LeaderBoardRepository.swift
- Escaper/Escaper/Presentation/LeaderBoard/LeaderBoardViewController.swift
- Escaper/Escaper/Presentation/LeaderBoard/LeaderBoardViewModel.swift
- Escaper/Escaper/Presentation/LeaderBoard/Views/RankView.swift
- Escaper/Escaper/Presentation/LeaderBoard/Views/TopRankView.swift
issue number : [#107](../issues/107) [#108](../issues/108) [#109](../issues/109) [#110](../issues/110)
close #107 
close #108 
close #109 
close #110
- LeaderBoard ViewModel
- LeaderBoard UseCase
- LeaderBoard Repository
- 유저의 수가 10명 이하일 경우만
> [E7 S1 T3], [E7 S1 T4], [E7 S1 T5], [E7 S1 T6] LeaderBoard ViewModel, domain단

- Escaper/Escaper/Infrastructure/FirebaseService.swift
issue number : [#158](../issues/158)
close #158
FirebaseSevice에 queryStore 구현
> [E6 S2 T5] Firebase에 업체 이름으로 검색을 구현한다.

- Escaper/Escaper/Common/Library/EDSKit.swift
- Escaper/Escaper/Presentation/LeaderBoard/LeaderBoardViewController.swift
- Escaper/Escaper/Presentation/LeaderBoard/Views/TopRankView.swift
- Escaper/Escaper/Presentation/RoomDetail/RoomDetailViewController.swift
- Escaper/Escaper/Presentation/RoomDetail/Views/RoomDetailInfoView.swift
- Escaper/Escaper/Presentation/RoomDetail/Views/RoomDetailUserRankView.swift
- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
|EDSKit의 case들을 알파벳 순으로 정렬|탭바 push, pop시에 자연스러운 애니메이션|네비게이셔바 push, pop시에 자연스러운 자연스러운 애니메이션 추가|
|:-:|:-:|:-:|
|<img width="231" alt="Screen Shot 2021-11-23 at 3 26 47 PM" src="https://user-images.githubusercontent.com/48627117/142979534-42f5801f-3086-4eb7-b9ef-3e64bacb60ec.png">|![탭바지워진다](https://user-images.githubusercontent.com/48627117/142979838-b1af087c-520e-4af6-b747-7649d71f5fc3.gif)|![네비게이션 바도 애니메이션](https://user-images.githubusercontent.com/48627117/143038836-0c2623fe-ff74-4dbd-a592-4f3a5a00ad34.gif)|
|**장르 추가**|**리더 보드 크기 조절**|**랭킹 넘버 오토레이 아웃 조절**|
|<img width="400" alt="Screen Shot 2021-11-23 at 11 05 01 PM" src="https://user-images.githubusercontent.com/48627117/143038599-4371efa8-174d-4e35-a5dd-6687a605ac2b.png">|<img width="400" alt="Screen Shot …
> 리뷰 반영 및 디테일뷰 탭바, 네비게이션바 설정

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Domain/Entities/Store.swift
- Escaper/Escaper/Domain/Interface/Repositories/StoreRepositoryInterface.swift
- Escaper/Escaper/Domain/UseCase/StoreUseCase.swift
- Escaper/Escaper/Infrastructure/DataMapping/StoreDTO.swift
- Escaper/Escaper/Infrastructure/FirebaseService.swift
- Escaper/Escaper/Infrastructure/StoreRepository.swift
- Escaper/Escaper/Presentation/Common/MainTabBarController.swift
- Escaper/Escaper/Presentation/Map/MapViewController.swift
- Escaper/Escaper/Presentation/Map/MapViewModel.swift
- Escaper/Escaper/Presentation/Map/StoreAnnotation.swift
- Escaper/Escaper/Presentation/Map/StoreListViewController.swift
- Escaper/Escaper/Presentation/Map/StoreOverViewTableViewCell.swift
- Escaper/Escaper/Presentation/StoreDetail/StoreDetailViewController.swift
issue number : [#163](../issues/163)
issue number : [#164](../issues/164)
issue number : [#165](../issues/165)
close #163
close #164
close #165
* Repository 구현
* UseCase 구현
* ViewModel 구현
> [E6 S2 T2, T3, T4] Repository, UseCase, ViewModel 구현한다.

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Infrastructure/UserRepository.swift
- Escaper/Escaper/Presentation/Map/StoreOverViewTableViewCell.swift
- Escaper/Escaper/Presentation/Record/Views/RecordGuideView.swift
SwiftLint 및 프로젝트 파일 리셋
컴파일 파일 리스트를 다 지우고 새롭게 파일을 추가했습니다.
이후 작업시 develop 브런치에 -f 로 pull 받기를 권유합니다. ㅎ
> SwiftLint 및 프로젝트 파일 리셋

- Escaper/Escaper/DataInjection/DataInjection.swift
- Escaper/Escaper/DataInjection/InjectionDTOs.swift
- Escaper/Escaper/Domain/Entities/Room.swift
- Escaper/Escaper/Infrastructure/DataMapping/RoomDTO.swift
- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
- Escaper/Escaper/Resources/extra.json
> Main 화면 로그인 여부에 따른 문구 보이도록 수정/ Data Injection 구조 변경

- Escaper/Escaper/Presentation/RoomList/RoomListViewController.swift
- Escaper/Escaper/Presentation/RoomList/Views/DistrictSelectButton.swift
issue number : [#180](../issues/180)
close #180
- 버그 수정
> [E5 T39] RoomListViewController 처음 로딩시 방 불러오지 않는 오류 해결

- Escaper/Escaper/Presentation/Login/SignUpViewController.swift
- Escaper/Escaper/Presentation/Login/Views/UserInputTextField.swift
- Escaper/Escaper/Presentation/Setting/Views/FeedBackView.swift
issue number : [#182](../issues/182)
close #182
제목 곧 내용
> Fix: Autocorrection, AutoCapitalization 을 false로 변경

- Escaper/Escaper/Presentation/Common/MainTabBarController.swift
Tabbar 클릭시 약한 진동 구현
디바이스로.. 하셔야.. 합니다. 찡끘   _<
> Tabbar 클릭시 약한 진동 구현

- Escaper/Escaper.xcodeproj/project.pbxproj
- Escaper/Escaper/Info.plist
- Escaper/Escaper/Infrastructure/FeedbackRepository.swift
- Escaper/Escaper/Presentation/AddRecord/AddRecordViewController.swift
- Escaper/Escaper/Presentation/Setting/SettingViewController.swift
- Escaper/Escaper/Presentation/Setting/Views/UserLogoutedView.swift
issue number : [#190](../issues/190)
close #190 
* Bundleid 수정
> [E11 T42] Appstore 등록을 위한 Bundleid 수정
